name: Checks before merge

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  hardhat-test:
    name: hardhat test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install
      - name: Run tests
        run: npm run test
  
  deploy-test:
    name: deploy-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install
      - name: Run deploy tests
        run: npm run test:stage || npm run test:prod

  linter-check:
    name: linters Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install
      - name: Run solhint
        run: npm run solhint
      - name: Run eslint
        run: npm run eslint

  coverage:
    name: test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install
      - name: run coverage
        run: npm run coverage
      # - name: send to Codecov
      #   run: npx codecov

  audit:
    name: slither audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y libsecret-1-dev libusb-1.0-0-dev libudev-dev
      - run: pip install slither-analyzer
      - name: Install Dependecies
        run: npm install
      - name: run slither
        run: npm run slither

